DRIVERS = [
    {"abbrev": "VER", "name": "Max Verstappen",   "team": "Red Bull Racing", "number": 1},
    {"abbrev": "NOR", "name": "Lando Norris",      "team": "McLaren",         "number": 4},
    {"abbrev": "LEC", "name": "Charles Leclerc",   "team": "Ferrari",         "number": 16},
    {"abbrev": "PIA", "name": "Oscar Piastri",     "team": "McLaren",         "number": 81},
    {"abbrev": "SAI", "name": "Carlos Sainz",      "team": "Williams",        "number": 55},
    {"abbrev": "RUS", "name": "George Russell",    "team": "Mercedes",        "number": 63},
    {"abbrev": "HAM", "name": "Lewis Hamilton",    "team": "Ferrari",         "number": 44},
    {"abbrev": "ANT", "name": "Kimi Antonelli",    "team": "Mercedes",        "number": 12},
    {"abbrev": "ALO", "name": "Fernando Alonso",   "team": "Aston Martin",    "number": 14},
    {"abbrev": "STR", "name": "Lance Stroll",      "team": "Aston Martin",    "number": 18},
    {"abbrev": "GAS", "name": "Pierre Gasly",      "team": "Alpine",          "number": 10},
    {"abbrev": "OCO", "name": "Esteban Ocon",      "team": "Haas F1 Team",    "number": 31},
    {"abbrev": "ALB", "name": "Alexander Albon",   "team": "Williams",        "number": 23},
    {"abbrev": "HAD", "name": "Isack Hadjar",      "team": "RB",              "number": 6},
    {"abbrev": "TSU", "name": "Yuki Tsunoda",      "team": "RB",              "number": 22},
    {"abbrev": "BOR", "name": "Gabriel Bortoleto", "team": "Kick Sauber",     "number": 5},
    {"abbrev": "HUL", "name": "Nico Hulkenberg",   "team": "Kick Sauber",     "number": 27},
    {"abbrev": "BEA", "name": "Oliver Bearman",    "team": "Haas F1 Team",    "number": 87},
    {"abbrev": "DOO", "name": "Jack Doohan",       "team": "Alpine",          "number": 7},
    {"abbrev": "LAW", "name": "Liam Lawson",       "team": "Red Bull Racing", "number": 30},
]

CIRCUITS = [
    {"name": "Bahrain Grand Prix",        "slug": "bahrain",      "country": "Bahrain",      "flag": "BH", "is_street": False},
    {"name": "Saudi Arabian Grand Prix",  "slug": "saudi-arabia", "country": "Saudi Arabia", "flag": "SA", "is_street": True},
    {"name": "Australian Grand Prix",     "slug": "australia",    "country": "Australia",    "flag": "AU", "is_street": True},
    {"name": "Japanese Grand Prix",       "slug": "japan",        "country": "Japan",        "flag": "JP", "is_street": False},
    {"name": "Chinese Grand Prix",        "slug": "china",        "country": "China",        "flag": "CN", "is_street": False},
    {"name": "Miami Grand Prix",          "slug": "miami",        "country": "USA",          "flag": "US", "is_street": True},
    {"name": "Emilia Romagna Grand Prix", "slug": "imola",        "country": "Italy",        "flag": "IT", "is_street": False},
    {"name": "Monaco Grand Prix",         "slug": "monaco",       "country": "Monaco",       "flag": "MC", "is_street": True},
    {"name": "Canadian Grand Prix",       "slug": "canada",       "country": "Canada",       "flag": "CA", "is_street": False},
    {"name": "Spanish Grand Prix",        "slug": "spain",        "country": "Spain",        "flag": "ES", "is_street": False},
    {"name": "Austrian Grand Prix",       "slug": "austria",      "country": "Austria",      "flag": "AT", "is_street": False},
    {"name": "British Grand Prix",        "slug": "britain",      "country": "UK",           "flag": "GB", "is_street": False},
    {"name": "Hungarian Grand Prix",      "slug": "hungary",      "country": "Hungary",      "flag": "HU", "is_street": False},
    {"name": "Belgian Grand Prix",        "slug": "belgium",      "country": "Belgium",      "flag": "BE", "is_street": False},
    {"name": "Dutch Grand Prix",          "slug": "netherlands",  "country": "Netherlands",  "flag": "NL", "is_street": False},
    {"name": "Italian Grand Prix",        "slug": "italy",        "country": "Italy",        "flag": "IT", "is_street": False},
    {"name": "Azerbaijan Grand Prix",     "slug": "azerbaijan",   "country": "Azerbaijan",   "flag": "AZ", "is_street": True},
    {"name": "Singapore Grand Prix",      "slug": "singapore",    "country": "Singapore",    "flag": "SG", "is_street": True},
    {"name": "United States Grand Prix",  "slug": "usa",          "country": "USA",          "flag": "US", "is_street": False},
    {"name": "Mexico City Grand Prix",    "slug": "mexico",       "country": "Mexico",       "flag": "MX", "is_street": False},
    {"name": "São Paulo Grand Prix",      "slug": "brazil",       "country": "Brazil",       "flag": "BR", "is_street": False},
    {"name": "Las Vegas Grand Prix",      "slug": "las-vegas",    "country": "USA",          "flag": "US", "is_street": True},
    {"name": "Qatar Grand Prix",          "slug": "qatar",        "country": "Qatar",        "flag": "QA", "is_street": False},
    {"name": "Abu Dhabi Grand Prix",      "slug": "abu-dhabi",    "country": "UAE",          "flag": "AE", "is_street": True},
]

COMPOUNDS = ["SOFT", "MEDIUM", "HARD", "INTERMEDIATE", "WET"]
SEASONS = [2022, 2023, 2024, 2025]
